minVersion: 0.23.1
github:
  owner: getsentry
  repo: arroyo
changelog: CHANGES.rst
changelogPolicy: auto
statusProvider:
  name: github
artifactProvider:
  name: github
targets:
  - name: github
  - name: pypi
