minVersion: 0.34.1
github:
  owner: getsentry
  repo: arroyo
changelogPolicy: auto
targets:
  - name: github
  - name: pypi
  # disabled until we merge https://github.com/getsentry/arroyo/pull/328
    # - name: crates
  - name: sentry-pypi
    internalPypiRepo: getsentry/pypi
