name: build

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  dist:
    name: Create wheel and source distribution
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - run: |
          python scripts/create_metrics_def_json.py
      - run: pip install wheel setuptools
      - run: python setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: dist/*
