name: build

on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  dist:
    name: Create wheel and source distribution
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # v2
        with:
          python-version: 3.12
      - run: |
          python scripts/create_metrics_def_json.py
      - run: pip install wheel setuptools
      - run: python setup.py sdist bdist_wheel
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: ${{ github.sha }}
          path: dist/*
