name: ci
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  typing:
    name: 'Type checking'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install
      - name: Run mypy
        run: |
          make lint
