name: ci
on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  linting:
    name: "Run linters"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-linter.txt
      - name: Run linter
        run: |
          black arroyo tests scripts
          flake8 arroyo tests scripts
  typing:
    name: "Type checking"
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install
      - name: Run mypy
        run: |
          make lint
  tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        python: [3.9, "3.10", "3.11", "3.12", "3.13"]
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Run Zookeeper and Kafka
        run: sh scripts/run-kafka.sh
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install
      - name: Run tests
        run: pytest -vv
