name: ci
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typing:
    name: 'Type checking'
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Run Zookeeper and Kafka
        run: |
          docker run \
            --name sentry_zookeeper \
            -d --network host \
            -e ZOOKEEPER_CLIENT_PORT=2181 \
            confluentinc/cp-zookeeper:4.1.0

          docker run \
            --name sentry_kafka \
            -d --network host \
            -e KAFKA_ZOOKEEPER_CONNECT=127.0.0.1:2181 \
            -e KAFKA_LISTENERS=INTERNAL://0.0.0.0:9093,EXTERNAL://0.0.0.0:9092 \
            -e KAFKA_ADVERTISED_LISTENERS=INTERNAL://127.0.0.1:9093,EXTERNAL://127.0.0.1:9092 \
            -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT \
            -e KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL \
            -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
            confluentinc/cp-kafka:5.1.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install
      - name: Run mypy
        run: |
          make lint
